POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 200,
    "make": "chev",
    "model": "gol",
    "year": 2024,
    "lng": 1,
    "lat": 1,
    "mileage": 200
}

### GET Report by id

### Get all Reports

### Patch approved
PATCH http://localhost:3000/reports/4
Content-Type: application/json

{
    "approved": true
}