POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 2400,
    "make": "ford",
    "model": "focus",
    "year": 2021,
    "lng": 1,
    "lat": 1,
    "mileage": 70000
}



### Get all Reports

### Patch approved
PATCH http://localhost:3000/reports/6
Content-Type: application/json

{
    "approved": true
}

### GET an Estimate for an existing vehicle
GET http://localhost:3000/reports?make=ford&model=focus&lng=1&year=2022&lat=1&mileage=2000